minimumReleaseAgeExclude:
  - '@valaxyjs/devtools@1.0.0-rc.10'
  - '@valaxyjs/utils@1.0.0-rc.10'
  - valaxy-theme-yun@1.0.0-rc.10
  - valaxy@1.0.0-rc.10
  - valaxy-addon-girls@0.1.0
  - eslint@10.9.1
shamefullyHoist: true
shellEmulator: true
trustLockfile: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - valaxy-addon-algolia@0.2.1
  - valaxy-addon-components@0.1.0
  - valaxy-addon-waline@0.2.1
packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - vue-demi
