minimumReleaseAgeExclude:
  - '@valaxyjs/devtools@1.0.0-beta.2'
  - '@valaxyjs/utils@1.0.0-beta.2'
  - valaxy-theme-yun@1.0.0-beta.2
  - valaxy@1.0.0-beta.2
shamefullyHoist: true
shellEmulator: true
trustLockfile: true
trustPolicy: no-downgrade
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
